// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Currency
{
	private final IMendixObject currencyMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Currency";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CurrencyKey("CurrencyKey"),
		CurrencyName("CurrencyName");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Currency(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Currency"));
	}

	protected Currency(IContext context, IMendixObject currencyMendixObject)
	{
		if (currencyMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Currency", currencyMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Currency");

		this.currencyMendixObject = currencyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Currency(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Currency create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.Currency");
		return new myfirstmodule.proxies.Currency(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Currency.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Currency initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Currency.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Currency initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Currency(context, mendixObject);
	}

	public static myfirstmodule.proxies.Currency load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Currency.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Currency> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Currency> result = new java.util.ArrayList<myfirstmodule.proxies.Currency>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Currency" + xpathConstraint))
			result.add(myfirstmodule.proxies.Currency.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CurrencyKey
	 */
	public final Integer getCurrencyKey()
	{
		return getCurrencyKey(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrencyKey
	 */
	public final Integer getCurrencyKey(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.CurrencyKey.toString());
	}

	/**
	 * Set value of CurrencyKey
	 * @param currencykey
	 */
	public final void setCurrencyKey(Integer currencykey)
	{
		setCurrencyKey(getContext(), currencykey);
	}

	/**
	 * Set value of CurrencyKey
	 * @param context
	 * @param currencykey
	 */
	public final void setCurrencyKey(IContext context, Integer currencykey)
	{
		getMendixObject().setValue(context, MemberNames.CurrencyKey.toString(), currencykey);
	}

	/**
	 * @return value of CurrencyName
	 */
	public final String getCurrencyName()
	{
		return getCurrencyName(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrencyName
	 */
	public final String getCurrencyName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CurrencyName.toString());
	}

	/**
	 * Set value of CurrencyName
	 * @param currencyname
	 */
	public final void setCurrencyName(String currencyname)
	{
		setCurrencyName(getContext(), currencyname);
	}

	/**
	 * Set value of CurrencyName
	 * @param context
	 * @param currencyname
	 */
	public final void setCurrencyName(IContext context, String currencyname)
	{
		getMendixObject().setValue(context, MemberNames.CurrencyName.toString(), currencyname);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return currencyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Currency that = (myfirstmodule.proxies.Currency) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Currency";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
