// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Date
{
	private final IMendixObject dateMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Date";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateKey("DateKey"),
		FullDateAlternateKey("FullDateAlternateKey"),
		DayNumberOfWeek("DayNumberOfWeek"),
		EnglishDayNameOfWeek("EnglishDayNameOfWeek"),
		SpanishDayNameOfWeek("SpanishDayNameOfWeek"),
		FrenchDayNameOfWeek("FrenchDayNameOfWeek"),
		DayNumberOfMonth("DayNumberOfMonth"),
		DayNumberOfYear("DayNumberOfYear"),
		WeekNumberOfYear("WeekNumberOfYear"),
		EnglishMonthName("EnglishMonthName"),
		SpanishMonthName("SpanishMonthName"),
		FrenchMonthName("FrenchMonthName"),
		MonthNumberOfYear("MonthNumberOfYear"),
		CalendarQuarter("CalendarQuarter"),
		CalendarYear("CalendarYear"),
		CalendarSemester("CalendarSemester"),
		FiscalQuarter("FiscalQuarter"),
		FiscalYear("FiscalYear"),
		FiscalSemester("FiscalSemester"),
		Date_InternetSales("MyFirstModule.Date_InternetSales");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Date(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Date"));
	}

	protected Date(IContext context, IMendixObject dateMendixObject)
	{
		if (dateMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Date", dateMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Date");

		this.dateMendixObject = dateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Date(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Date create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.Date");
		return new myfirstmodule.proxies.Date(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Date.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Date initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Date.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Date initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Date(context, mendixObject);
	}

	public static myfirstmodule.proxies.Date load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Date.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Date> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Date> result = new java.util.ArrayList<myfirstmodule.proxies.Date>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Date" + xpathConstraint))
			result.add(myfirstmodule.proxies.Date.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DateKey
	 */
	public final Integer getDateKey()
	{
		return getDateKey(getContext());
	}

	/**
	 * @param context
	 * @return value of DateKey
	 */
	public final Integer getDateKey(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.DateKey.toString());
	}

	/**
	 * Set value of DateKey
	 * @param datekey
	 */
	public final void setDateKey(Integer datekey)
	{
		setDateKey(getContext(), datekey);
	}

	/**
	 * Set value of DateKey
	 * @param context
	 * @param datekey
	 */
	public final void setDateKey(IContext context, Integer datekey)
	{
		getMendixObject().setValue(context, MemberNames.DateKey.toString(), datekey);
	}

	/**
	 * @return value of FullDateAlternateKey
	 */
	public final java.util.Date getFullDateAlternateKey()
	{
		return getFullDateAlternateKey(getContext());
	}

	/**
	 * @param context
	 * @return value of FullDateAlternateKey
	 */
	public final java.util.Date getFullDateAlternateKey(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.FullDateAlternateKey.toString());
	}

	/**
	 * Set value of FullDateAlternateKey
	 * @param fulldatealternatekey
	 */
	public final void setFullDateAlternateKey(java.util.Date fulldatealternatekey)
	{
		setFullDateAlternateKey(getContext(), fulldatealternatekey);
	}

	/**
	 * Set value of FullDateAlternateKey
	 * @param context
	 * @param fulldatealternatekey
	 */
	public final void setFullDateAlternateKey(IContext context, java.util.Date fulldatealternatekey)
	{
		getMendixObject().setValue(context, MemberNames.FullDateAlternateKey.toString(), fulldatealternatekey);
	}

	/**
	 * @return value of DayNumberOfWeek
	 */
	public final Integer getDayNumberOfWeek()
	{
		return getDayNumberOfWeek(getContext());
	}

	/**
	 * @param context
	 * @return value of DayNumberOfWeek
	 */
	public final Integer getDayNumberOfWeek(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.DayNumberOfWeek.toString());
	}

	/**
	 * Set value of DayNumberOfWeek
	 * @param daynumberofweek
	 */
	public final void setDayNumberOfWeek(Integer daynumberofweek)
	{
		setDayNumberOfWeek(getContext(), daynumberofweek);
	}

	/**
	 * Set value of DayNumberOfWeek
	 * @param context
	 * @param daynumberofweek
	 */
	public final void setDayNumberOfWeek(IContext context, Integer daynumberofweek)
	{
		getMendixObject().setValue(context, MemberNames.DayNumberOfWeek.toString(), daynumberofweek);
	}

	/**
	 * @return value of EnglishDayNameOfWeek
	 */
	public final String getEnglishDayNameOfWeek()
	{
		return getEnglishDayNameOfWeek(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishDayNameOfWeek
	 */
	public final String getEnglishDayNameOfWeek(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishDayNameOfWeek.toString());
	}

	/**
	 * Set value of EnglishDayNameOfWeek
	 * @param englishdaynameofweek
	 */
	public final void setEnglishDayNameOfWeek(String englishdaynameofweek)
	{
		setEnglishDayNameOfWeek(getContext(), englishdaynameofweek);
	}

	/**
	 * Set value of EnglishDayNameOfWeek
	 * @param context
	 * @param englishdaynameofweek
	 */
	public final void setEnglishDayNameOfWeek(IContext context, String englishdaynameofweek)
	{
		getMendixObject().setValue(context, MemberNames.EnglishDayNameOfWeek.toString(), englishdaynameofweek);
	}

	/**
	 * @return value of SpanishDayNameOfWeek
	 */
	public final String getSpanishDayNameOfWeek()
	{
		return getSpanishDayNameOfWeek(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanishDayNameOfWeek
	 */
	public final String getSpanishDayNameOfWeek(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SpanishDayNameOfWeek.toString());
	}

	/**
	 * Set value of SpanishDayNameOfWeek
	 * @param spanishdaynameofweek
	 */
	public final void setSpanishDayNameOfWeek(String spanishdaynameofweek)
	{
		setSpanishDayNameOfWeek(getContext(), spanishdaynameofweek);
	}

	/**
	 * Set value of SpanishDayNameOfWeek
	 * @param context
	 * @param spanishdaynameofweek
	 */
	public final void setSpanishDayNameOfWeek(IContext context, String spanishdaynameofweek)
	{
		getMendixObject().setValue(context, MemberNames.SpanishDayNameOfWeek.toString(), spanishdaynameofweek);
	}

	/**
	 * @return value of FrenchDayNameOfWeek
	 */
	public final String getFrenchDayNameOfWeek()
	{
		return getFrenchDayNameOfWeek(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchDayNameOfWeek
	 */
	public final String getFrenchDayNameOfWeek(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchDayNameOfWeek.toString());
	}

	/**
	 * Set value of FrenchDayNameOfWeek
	 * @param frenchdaynameofweek
	 */
	public final void setFrenchDayNameOfWeek(String frenchdaynameofweek)
	{
		setFrenchDayNameOfWeek(getContext(), frenchdaynameofweek);
	}

	/**
	 * Set value of FrenchDayNameOfWeek
	 * @param context
	 * @param frenchdaynameofweek
	 */
	public final void setFrenchDayNameOfWeek(IContext context, String frenchdaynameofweek)
	{
		getMendixObject().setValue(context, MemberNames.FrenchDayNameOfWeek.toString(), frenchdaynameofweek);
	}

	/**
	 * @return value of DayNumberOfMonth
	 */
	public final Integer getDayNumberOfMonth()
	{
		return getDayNumberOfMonth(getContext());
	}

	/**
	 * @param context
	 * @return value of DayNumberOfMonth
	 */
	public final Integer getDayNumberOfMonth(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.DayNumberOfMonth.toString());
	}

	/**
	 * Set value of DayNumberOfMonth
	 * @param daynumberofmonth
	 */
	public final void setDayNumberOfMonth(Integer daynumberofmonth)
	{
		setDayNumberOfMonth(getContext(), daynumberofmonth);
	}

	/**
	 * Set value of DayNumberOfMonth
	 * @param context
	 * @param daynumberofmonth
	 */
	public final void setDayNumberOfMonth(IContext context, Integer daynumberofmonth)
	{
		getMendixObject().setValue(context, MemberNames.DayNumberOfMonth.toString(), daynumberofmonth);
	}

	/**
	 * @return value of DayNumberOfYear
	 */
	public final Integer getDayNumberOfYear()
	{
		return getDayNumberOfYear(getContext());
	}

	/**
	 * @param context
	 * @return value of DayNumberOfYear
	 */
	public final Integer getDayNumberOfYear(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.DayNumberOfYear.toString());
	}

	/**
	 * Set value of DayNumberOfYear
	 * @param daynumberofyear
	 */
	public final void setDayNumberOfYear(Integer daynumberofyear)
	{
		setDayNumberOfYear(getContext(), daynumberofyear);
	}

	/**
	 * Set value of DayNumberOfYear
	 * @param context
	 * @param daynumberofyear
	 */
	public final void setDayNumberOfYear(IContext context, Integer daynumberofyear)
	{
		getMendixObject().setValue(context, MemberNames.DayNumberOfYear.toString(), daynumberofyear);
	}

	/**
	 * @return value of WeekNumberOfYear
	 */
	public final Integer getWeekNumberOfYear()
	{
		return getWeekNumberOfYear(getContext());
	}

	/**
	 * @param context
	 * @return value of WeekNumberOfYear
	 */
	public final Integer getWeekNumberOfYear(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.WeekNumberOfYear.toString());
	}

	/**
	 * Set value of WeekNumberOfYear
	 * @param weeknumberofyear
	 */
	public final void setWeekNumberOfYear(Integer weeknumberofyear)
	{
		setWeekNumberOfYear(getContext(), weeknumberofyear);
	}

	/**
	 * Set value of WeekNumberOfYear
	 * @param context
	 * @param weeknumberofyear
	 */
	public final void setWeekNumberOfYear(IContext context, Integer weeknumberofyear)
	{
		getMendixObject().setValue(context, MemberNames.WeekNumberOfYear.toString(), weeknumberofyear);
	}

	/**
	 * @return value of EnglishMonthName
	 */
	public final String getEnglishMonthName()
	{
		return getEnglishMonthName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishMonthName
	 */
	public final String getEnglishMonthName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishMonthName.toString());
	}

	/**
	 * Set value of EnglishMonthName
	 * @param englishmonthname
	 */
	public final void setEnglishMonthName(String englishmonthname)
	{
		setEnglishMonthName(getContext(), englishmonthname);
	}

	/**
	 * Set value of EnglishMonthName
	 * @param context
	 * @param englishmonthname
	 */
	public final void setEnglishMonthName(IContext context, String englishmonthname)
	{
		getMendixObject().setValue(context, MemberNames.EnglishMonthName.toString(), englishmonthname);
	}

	/**
	 * @return value of SpanishMonthName
	 */
	public final String getSpanishMonthName()
	{
		return getSpanishMonthName(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanishMonthName
	 */
	public final String getSpanishMonthName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SpanishMonthName.toString());
	}

	/**
	 * Set value of SpanishMonthName
	 * @param spanishmonthname
	 */
	public final void setSpanishMonthName(String spanishmonthname)
	{
		setSpanishMonthName(getContext(), spanishmonthname);
	}

	/**
	 * Set value of SpanishMonthName
	 * @param context
	 * @param spanishmonthname
	 */
	public final void setSpanishMonthName(IContext context, String spanishmonthname)
	{
		getMendixObject().setValue(context, MemberNames.SpanishMonthName.toString(), spanishmonthname);
	}

	/**
	 * @return value of FrenchMonthName
	 */
	public final String getFrenchMonthName()
	{
		return getFrenchMonthName(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchMonthName
	 */
	public final String getFrenchMonthName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchMonthName.toString());
	}

	/**
	 * Set value of FrenchMonthName
	 * @param frenchmonthname
	 */
	public final void setFrenchMonthName(String frenchmonthname)
	{
		setFrenchMonthName(getContext(), frenchmonthname);
	}

	/**
	 * Set value of FrenchMonthName
	 * @param context
	 * @param frenchmonthname
	 */
	public final void setFrenchMonthName(IContext context, String frenchmonthname)
	{
		getMendixObject().setValue(context, MemberNames.FrenchMonthName.toString(), frenchmonthname);
	}

	/**
	 * @return value of MonthNumberOfYear
	 */
	public final Integer getMonthNumberOfYear()
	{
		return getMonthNumberOfYear(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthNumberOfYear
	 */
	public final Integer getMonthNumberOfYear(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.MonthNumberOfYear.toString());
	}

	/**
	 * Set value of MonthNumberOfYear
	 * @param monthnumberofyear
	 */
	public final void setMonthNumberOfYear(Integer monthnumberofyear)
	{
		setMonthNumberOfYear(getContext(), monthnumberofyear);
	}

	/**
	 * Set value of MonthNumberOfYear
	 * @param context
	 * @param monthnumberofyear
	 */
	public final void setMonthNumberOfYear(IContext context, Integer monthnumberofyear)
	{
		getMendixObject().setValue(context, MemberNames.MonthNumberOfYear.toString(), monthnumberofyear);
	}

	/**
	 * @return value of CalendarQuarter
	 */
	public final Integer getCalendarQuarter()
	{
		return getCalendarQuarter(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarQuarter
	 */
	public final Integer getCalendarQuarter(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.CalendarQuarter.toString());
	}

	/**
	 * Set value of CalendarQuarter
	 * @param calendarquarter
	 */
	public final void setCalendarQuarter(Integer calendarquarter)
	{
		setCalendarQuarter(getContext(), calendarquarter);
	}

	/**
	 * Set value of CalendarQuarter
	 * @param context
	 * @param calendarquarter
	 */
	public final void setCalendarQuarter(IContext context, Integer calendarquarter)
	{
		getMendixObject().setValue(context, MemberNames.CalendarQuarter.toString(), calendarquarter);
	}

	/**
	 * @return value of CalendarYear
	 */
	public final Integer getCalendarYear()
	{
		return getCalendarYear(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarYear
	 */
	public final Integer getCalendarYear(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.CalendarYear.toString());
	}

	/**
	 * Set value of CalendarYear
	 * @param calendaryear
	 */
	public final void setCalendarYear(Integer calendaryear)
	{
		setCalendarYear(getContext(), calendaryear);
	}

	/**
	 * Set value of CalendarYear
	 * @param context
	 * @param calendaryear
	 */
	public final void setCalendarYear(IContext context, Integer calendaryear)
	{
		getMendixObject().setValue(context, MemberNames.CalendarYear.toString(), calendaryear);
	}

	/**
	 * @return value of CalendarSemester
	 */
	public final Integer getCalendarSemester()
	{
		return getCalendarSemester(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarSemester
	 */
	public final Integer getCalendarSemester(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.CalendarSemester.toString());
	}

	/**
	 * Set value of CalendarSemester
	 * @param calendarsemester
	 */
	public final void setCalendarSemester(Integer calendarsemester)
	{
		setCalendarSemester(getContext(), calendarsemester);
	}

	/**
	 * Set value of CalendarSemester
	 * @param context
	 * @param calendarsemester
	 */
	public final void setCalendarSemester(IContext context, Integer calendarsemester)
	{
		getMendixObject().setValue(context, MemberNames.CalendarSemester.toString(), calendarsemester);
	}

	/**
	 * @return value of FiscalQuarter
	 */
	public final Integer getFiscalQuarter()
	{
		return getFiscalQuarter(getContext());
	}

	/**
	 * @param context
	 * @return value of FiscalQuarter
	 */
	public final Integer getFiscalQuarter(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.FiscalQuarter.toString());
	}

	/**
	 * Set value of FiscalQuarter
	 * @param fiscalquarter
	 */
	public final void setFiscalQuarter(Integer fiscalquarter)
	{
		setFiscalQuarter(getContext(), fiscalquarter);
	}

	/**
	 * Set value of FiscalQuarter
	 * @param context
	 * @param fiscalquarter
	 */
	public final void setFiscalQuarter(IContext context, Integer fiscalquarter)
	{
		getMendixObject().setValue(context, MemberNames.FiscalQuarter.toString(), fiscalquarter);
	}

	/**
	 * @return value of FiscalYear
	 */
	public final Integer getFiscalYear()
	{
		return getFiscalYear(getContext());
	}

	/**
	 * @param context
	 * @return value of FiscalYear
	 */
	public final Integer getFiscalYear(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.FiscalYear.toString());
	}

	/**
	 * Set value of FiscalYear
	 * @param fiscalyear
	 */
	public final void setFiscalYear(Integer fiscalyear)
	{
		setFiscalYear(getContext(), fiscalyear);
	}

	/**
	 * Set value of FiscalYear
	 * @param context
	 * @param fiscalyear
	 */
	public final void setFiscalYear(IContext context, Integer fiscalyear)
	{
		getMendixObject().setValue(context, MemberNames.FiscalYear.toString(), fiscalyear);
	}

	/**
	 * @return value of FiscalSemester
	 */
	public final Integer getFiscalSemester()
	{
		return getFiscalSemester(getContext());
	}

	/**
	 * @param context
	 * @return value of FiscalSemester
	 */
	public final Integer getFiscalSemester(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.FiscalSemester.toString());
	}

	/**
	 * Set value of FiscalSemester
	 * @param fiscalsemester
	 */
	public final void setFiscalSemester(Integer fiscalsemester)
	{
		setFiscalSemester(getContext(), fiscalsemester);
	}

	/**
	 * Set value of FiscalSemester
	 * @param context
	 * @param fiscalsemester
	 */
	public final void setFiscalSemester(IContext context, Integer fiscalsemester)
	{
		getMendixObject().setValue(context, MemberNames.FiscalSemester.toString(), fiscalsemester);
	}

	/**
	 * @return value of Date_InternetSales
	 */
	public final myfirstmodule.proxies.InternetSales getDate_InternetSales() throws CoreException
	{
		return getDate_InternetSales(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_InternetSales
	 */
	public final myfirstmodule.proxies.InternetSales getDate_InternetSales(IContext context) throws CoreException
	{
		myfirstmodule.proxies.InternetSales result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Date_InternetSales.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.InternetSales.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Date_InternetSales
	 * @param date_internetsales
	 */
	public final void setDate_InternetSales(myfirstmodule.proxies.InternetSales date_internetsales)
	{
		setDate_InternetSales(getContext(), date_internetsales);
	}

	/**
	 * Set value of Date_InternetSales
	 * @param context
	 * @param date_internetsales
	 */
	public final void setDate_InternetSales(IContext context, myfirstmodule.proxies.InternetSales date_internetsales)
	{
		if (date_internetsales == null)
			getMendixObject().setValue(context, MemberNames.Date_InternetSales.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Date_InternetSales.toString(), date_internetsales.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return dateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Date that = (myfirstmodule.proxies.Date) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Date";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
