// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.objectmanagement.member.MendixBinary;

/**
 * 
 */
public class Product
{
	private final IMendixObject productMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Product";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProductKey("ProductKey"),
		WeightUnitMeasureCode("WeightUnitMeasureCode"),
		SizeUnitMeasureCode("SizeUnitMeasureCode"),
		EnglishProductName("EnglishProductName"),
		SpanishProductName("SpanishProductName"),
		FrenchProductName("FrenchProductName"),
		StandardCost("StandardCost"),
		FinishedGoodsFlag("FinishedGoodsFlag"),
		Color("Color"),
		SafetyStockLevel("SafetyStockLevel"),
		ReorderPoint("ReorderPoint"),
		ListPrice("ListPrice"),
		Size("Size"),
		SizeRange("SizeRange"),
		Weight("Weight"),
		DaysToManufacture("DaysToManufacture"),
		ProductLine("ProductLine"),
		DealerPrice("DealerPrice"),
		ClassS("ClassS"),
		Style("Style"),
		ModelName("ModelName"),
		LargePhoto("LargePhoto"),
		EnglishDescription("EnglishDescription"),
		FrenchDescription("FrenchDescription"),
		ChineseDescription("ChineseDescription"),
		ArabicDescription("ArabicDescription"),
		HebrewDescription("HebrewDescription"),
		ThaiDescription("ThaiDescription"),
		GermanDescription("GermanDescription"),
		JapaneseDescription("JapaneseDescription"),
		TurkishDescription("TurkishDescription"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		Status("Status"),
		Product_ProductSubcategory("MyFirstModule.Product_ProductSubcategory");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Product(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Product"));
	}

	protected Product(IContext context, IMendixObject productMendixObject)
	{
		if (productMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Product", productMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Product");

		this.productMendixObject = productMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Product(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Product create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.Product");
		return new myfirstmodule.proxies.Product(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Product.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Product initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Product.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Product initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Product(context, mendixObject);
	}

	public static myfirstmodule.proxies.Product load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Product.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Product> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Product> result = new java.util.ArrayList<myfirstmodule.proxies.Product>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Product" + xpathConstraint))
			result.add(myfirstmodule.proxies.Product.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProductKey
	 */
	public final Integer getProductKey()
	{
		return getProductKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductKey
	 */
	public final Integer getProductKey(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.ProductKey.toString());
	}

	/**
	 * Set value of ProductKey
	 * @param productkey
	 */
	public final void setProductKey(Integer productkey)
	{
		setProductKey(getContext(), productkey);
	}

	/**
	 * Set value of ProductKey
	 * @param context
	 * @param productkey
	 */
	public final void setProductKey(IContext context, Integer productkey)
	{
		getMendixObject().setValue(context, MemberNames.ProductKey.toString(), productkey);
	}

	/**
	 * @return value of WeightUnitMeasureCode
	 */
	public final String getWeightUnitMeasureCode()
	{
		return getWeightUnitMeasureCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WeightUnitMeasureCode
	 */
	public final String getWeightUnitMeasureCode(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.WeightUnitMeasureCode.toString());
	}

	/**
	 * Set value of WeightUnitMeasureCode
	 * @param weightunitmeasurecode
	 */
	public final void setWeightUnitMeasureCode(String weightunitmeasurecode)
	{
		setWeightUnitMeasureCode(getContext(), weightunitmeasurecode);
	}

	/**
	 * Set value of WeightUnitMeasureCode
	 * @param context
	 * @param weightunitmeasurecode
	 */
	public final void setWeightUnitMeasureCode(IContext context, String weightunitmeasurecode)
	{
		getMendixObject().setValue(context, MemberNames.WeightUnitMeasureCode.toString(), weightunitmeasurecode);
	}

	/**
	 * @return value of SizeUnitMeasureCode
	 */
	public final String getSizeUnitMeasureCode()
	{
		return getSizeUnitMeasureCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SizeUnitMeasureCode
	 */
	public final String getSizeUnitMeasureCode(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SizeUnitMeasureCode.toString());
	}

	/**
	 * Set value of SizeUnitMeasureCode
	 * @param sizeunitmeasurecode
	 */
	public final void setSizeUnitMeasureCode(String sizeunitmeasurecode)
	{
		setSizeUnitMeasureCode(getContext(), sizeunitmeasurecode);
	}

	/**
	 * Set value of SizeUnitMeasureCode
	 * @param context
	 * @param sizeunitmeasurecode
	 */
	public final void setSizeUnitMeasureCode(IContext context, String sizeunitmeasurecode)
	{
		getMendixObject().setValue(context, MemberNames.SizeUnitMeasureCode.toString(), sizeunitmeasurecode);
	}

	/**
	 * @return value of EnglishProductName
	 */
	public final String getEnglishProductName()
	{
		return getEnglishProductName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishProductName
	 */
	public final String getEnglishProductName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishProductName.toString());
	}

	/**
	 * Set value of EnglishProductName
	 * @param englishproductname
	 */
	public final void setEnglishProductName(String englishproductname)
	{
		setEnglishProductName(getContext(), englishproductname);
	}

	/**
	 * Set value of EnglishProductName
	 * @param context
	 * @param englishproductname
	 */
	public final void setEnglishProductName(IContext context, String englishproductname)
	{
		getMendixObject().setValue(context, MemberNames.EnglishProductName.toString(), englishproductname);
	}

	/**
	 * @return value of SpanishProductName
	 */
	public final String getSpanishProductName()
	{
		return getSpanishProductName(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanishProductName
	 */
	public final String getSpanishProductName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SpanishProductName.toString());
	}

	/**
	 * Set value of SpanishProductName
	 * @param spanishproductname
	 */
	public final void setSpanishProductName(String spanishproductname)
	{
		setSpanishProductName(getContext(), spanishproductname);
	}

	/**
	 * Set value of SpanishProductName
	 * @param context
	 * @param spanishproductname
	 */
	public final void setSpanishProductName(IContext context, String spanishproductname)
	{
		getMendixObject().setValue(context, MemberNames.SpanishProductName.toString(), spanishproductname);
	}

	/**
	 * @return value of FrenchProductName
	 */
	public final String getFrenchProductName()
	{
		return getFrenchProductName(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchProductName
	 */
	public final String getFrenchProductName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchProductName.toString());
	}

	/**
	 * Set value of FrenchProductName
	 * @param frenchproductname
	 */
	public final void setFrenchProductName(String frenchproductname)
	{
		setFrenchProductName(getContext(), frenchproductname);
	}

	/**
	 * Set value of FrenchProductName
	 * @param context
	 * @param frenchproductname
	 */
	public final void setFrenchProductName(IContext context, String frenchproductname)
	{
		getMendixObject().setValue(context, MemberNames.FrenchProductName.toString(), frenchproductname);
	}

	/**
	 * @return value of StandardCost
	 */
	public final Double getStandardCost()
	{
		return getStandardCost(getContext());
	}

	/**
	 * @param context
	 * @return value of StandardCost
	 */
	public final Double getStandardCost(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.StandardCost.toString());
	}

	/**
	 * Set value of StandardCost
	 * @param standardcost
	 */
	public final void setStandardCost(Double standardcost)
	{
		setStandardCost(getContext(), standardcost);
	}

	/**
	 * Set value of StandardCost
	 * @param context
	 * @param standardcost
	 */
	public final void setStandardCost(IContext context, Double standardcost)
	{
		getMendixObject().setValue(context, MemberNames.StandardCost.toString(), standardcost);
	}

	/**
	 * @return value of FinishedGoodsFlag
	 */
	public final Boolean getFinishedGoodsFlag()
	{
		return getFinishedGoodsFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of FinishedGoodsFlag
	 */
	public final Boolean getFinishedGoodsFlag(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.FinishedGoodsFlag.toString());
	}

	/**
	 * Set value of FinishedGoodsFlag
	 * @param finishedgoodsflag
	 */
	public final void setFinishedGoodsFlag(Boolean finishedgoodsflag)
	{
		setFinishedGoodsFlag(getContext(), finishedgoodsflag);
	}

	/**
	 * Set value of FinishedGoodsFlag
	 * @param context
	 * @param finishedgoodsflag
	 */
	public final void setFinishedGoodsFlag(IContext context, Boolean finishedgoodsflag)
	{
		getMendixObject().setValue(context, MemberNames.FinishedGoodsFlag.toString(), finishedgoodsflag);
	}

	/**
	 * @return value of Color
	 */
	public final String getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final String getColor(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Color.toString());
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(String color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(IContext context, String color)
	{
		getMendixObject().setValue(context, MemberNames.Color.toString(), color);
	}

	/**
	 * @return value of SafetyStockLevel
	 */
	public final Integer getSafetyStockLevel()
	{
		return getSafetyStockLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of SafetyStockLevel
	 */
	public final Integer getSafetyStockLevel(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.SafetyStockLevel.toString());
	}

	/**
	 * Set value of SafetyStockLevel
	 * @param safetystocklevel
	 */
	public final void setSafetyStockLevel(Integer safetystocklevel)
	{
		setSafetyStockLevel(getContext(), safetystocklevel);
	}

	/**
	 * Set value of SafetyStockLevel
	 * @param context
	 * @param safetystocklevel
	 */
	public final void setSafetyStockLevel(IContext context, Integer safetystocklevel)
	{
		getMendixObject().setValue(context, MemberNames.SafetyStockLevel.toString(), safetystocklevel);
	}

	/**
	 * @return value of ReorderPoint
	 */
	public final Integer getReorderPoint()
	{
		return getReorderPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of ReorderPoint
	 */
	public final Integer getReorderPoint(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.ReorderPoint.toString());
	}

	/**
	 * Set value of ReorderPoint
	 * @param reorderpoint
	 */
	public final void setReorderPoint(Integer reorderpoint)
	{
		setReorderPoint(getContext(), reorderpoint);
	}

	/**
	 * Set value of ReorderPoint
	 * @param context
	 * @param reorderpoint
	 */
	public final void setReorderPoint(IContext context, Integer reorderpoint)
	{
		getMendixObject().setValue(context, MemberNames.ReorderPoint.toString(), reorderpoint);
	}

	/**
	 * @return value of ListPrice
	 */
	public final Double getListPrice()
	{
		return getListPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of ListPrice
	 */
	public final Double getListPrice(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.ListPrice.toString());
	}

	/**
	 * Set value of ListPrice
	 * @param listprice
	 */
	public final void setListPrice(Double listprice)
	{
		setListPrice(getContext(), listprice);
	}

	/**
	 * Set value of ListPrice
	 * @param context
	 * @param listprice
	 */
	public final void setListPrice(IContext context, Double listprice)
	{
		getMendixObject().setValue(context, MemberNames.ListPrice.toString(), listprice);
	}

	/**
	 * @return value of Size
	 */
	public final String getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final String getSize(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(String size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(IContext context, String size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of SizeRange
	 */
	public final String getSizeRange()
	{
		return getSizeRange(getContext());
	}

	/**
	 * @param context
	 * @return value of SizeRange
	 */
	public final String getSizeRange(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SizeRange.toString());
	}

	/**
	 * Set value of SizeRange
	 * @param sizerange
	 */
	public final void setSizeRange(String sizerange)
	{
		setSizeRange(getContext(), sizerange);
	}

	/**
	 * Set value of SizeRange
	 * @param context
	 * @param sizerange
	 */
	public final void setSizeRange(IContext context, String sizerange)
	{
		getMendixObject().setValue(context, MemberNames.SizeRange.toString(), sizerange);
	}

	/**
	 * @return value of Weight
	 */
	public final Double getWeight()
	{
		return getWeight(getContext());
	}

	/**
	 * @param context
	 * @return value of Weight
	 */
	public final Double getWeight(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.Weight.toString());
	}

	/**
	 * Set value of Weight
	 * @param weight
	 */
	public final void setWeight(Double weight)
	{
		setWeight(getContext(), weight);
	}

	/**
	 * Set value of Weight
	 * @param context
	 * @param weight
	 */
	public final void setWeight(IContext context, Double weight)
	{
		getMendixObject().setValue(context, MemberNames.Weight.toString(), weight);
	}

	/**
	 * @return value of DaysToManufacture
	 */
	public final Integer getDaysToManufacture()
	{
		return getDaysToManufacture(getContext());
	}

	/**
	 * @param context
	 * @return value of DaysToManufacture
	 */
	public final Integer getDaysToManufacture(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.DaysToManufacture.toString());
	}

	/**
	 * Set value of DaysToManufacture
	 * @param daystomanufacture
	 */
	public final void setDaysToManufacture(Integer daystomanufacture)
	{
		setDaysToManufacture(getContext(), daystomanufacture);
	}

	/**
	 * Set value of DaysToManufacture
	 * @param context
	 * @param daystomanufacture
	 */
	public final void setDaysToManufacture(IContext context, Integer daystomanufacture)
	{
		getMendixObject().setValue(context, MemberNames.DaysToManufacture.toString(), daystomanufacture);
	}

	/**
	 * @return value of ProductLine
	 */
	public final String getProductLine()
	{
		return getProductLine(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductLine
	 */
	public final String getProductLine(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ProductLine.toString());
	}

	/**
	 * Set value of ProductLine
	 * @param productline
	 */
	public final void setProductLine(String productline)
	{
		setProductLine(getContext(), productline);
	}

	/**
	 * Set value of ProductLine
	 * @param context
	 * @param productline
	 */
	public final void setProductLine(IContext context, String productline)
	{
		getMendixObject().setValue(context, MemberNames.ProductLine.toString(), productline);
	}

	/**
	 * @return value of DealerPrice
	 */
	public final Double getDealerPrice()
	{
		return getDealerPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of DealerPrice
	 */
	public final Double getDealerPrice(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.DealerPrice.toString());
	}

	/**
	 * Set value of DealerPrice
	 * @param dealerprice
	 */
	public final void setDealerPrice(Double dealerprice)
	{
		setDealerPrice(getContext(), dealerprice);
	}

	/**
	 * Set value of DealerPrice
	 * @param context
	 * @param dealerprice
	 */
	public final void setDealerPrice(IContext context, Double dealerprice)
	{
		getMendixObject().setValue(context, MemberNames.DealerPrice.toString(), dealerprice);
	}

	/**
	 * @return value of ClassS
	 */
	public final String getClassS()
	{
		return getClassS(getContext());
	}

	/**
	 * @param context
	 * @return value of ClassS
	 */
	public final String getClassS(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ClassS.toString());
	}

	/**
	 * Set value of ClassS
	 * @param classs
	 */
	public final void setClassS(String classs)
	{
		setClassS(getContext(), classs);
	}

	/**
	 * Set value of ClassS
	 * @param context
	 * @param classs
	 */
	public final void setClassS(IContext context, String classs)
	{
		getMendixObject().setValue(context, MemberNames.ClassS.toString(), classs);
	}

	/**
	 * @return value of Style
	 */
	public final String getStyle()
	{
		return getStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of Style
	 */
	public final String getStyle(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Style.toString());
	}

	/**
	 * Set value of Style
	 * @param style
	 */
	public final void setStyle(String style)
	{
		setStyle(getContext(), style);
	}

	/**
	 * Set value of Style
	 * @param context
	 * @param style
	 */
	public final void setStyle(IContext context, String style)
	{
		getMendixObject().setValue(context, MemberNames.Style.toString(), style);
	}

	/**
	 * @return value of ModelName
	 */
	public final String getModelName()
	{
		return getModelName(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelName
	 */
	public final String getModelName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ModelName.toString());
	}

	/**
	 * Set value of ModelName
	 * @param modelname
	 */
	public final void setModelName(String modelname)
	{
		setModelName(getContext(), modelname);
	}

	/**
	 * Set value of ModelName
	 * @param context
	 * @param modelname
	 */
	public final void setModelName(IContext context, String modelname)
	{
		getMendixObject().setValue(context, MemberNames.ModelName.toString(), modelname);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getLargePhoto(IContext context, java.io.OutputStream outputStream)
	{
		MendixBinary binary = (MendixBinary) getMendixObject().getMember(context, MemberNames.LargePhoto.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setLargePhoto(IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == IMendixObject.ObjectState.INSTANTIATED)
			try { commit(); } catch (CoreException ex) { }
		MendixBinary binary = (MendixBinary) getMendixObject().getMember(context, MemberNames.LargePhoto.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @return value of EnglishDescription
	 */
	public final String getEnglishDescription()
	{
		return getEnglishDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishDescription
	 */
	public final String getEnglishDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishDescription.toString());
	}

	/**
	 * Set value of EnglishDescription
	 * @param englishdescription
	 */
	public final void setEnglishDescription(String englishdescription)
	{
		setEnglishDescription(getContext(), englishdescription);
	}

	/**
	 * Set value of EnglishDescription
	 * @param context
	 * @param englishdescription
	 */
	public final void setEnglishDescription(IContext context, String englishdescription)
	{
		getMendixObject().setValue(context, MemberNames.EnglishDescription.toString(), englishdescription);
	}

	/**
	 * @return value of FrenchDescription
	 */
	public final String getFrenchDescription()
	{
		return getFrenchDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchDescription
	 */
	public final String getFrenchDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchDescription.toString());
	}

	/**
	 * Set value of FrenchDescription
	 * @param frenchdescription
	 */
	public final void setFrenchDescription(String frenchdescription)
	{
		setFrenchDescription(getContext(), frenchdescription);
	}

	/**
	 * Set value of FrenchDescription
	 * @param context
	 * @param frenchdescription
	 */
	public final void setFrenchDescription(IContext context, String frenchdescription)
	{
		getMendixObject().setValue(context, MemberNames.FrenchDescription.toString(), frenchdescription);
	}

	/**
	 * @return value of ChineseDescription
	 */
	public final String getChineseDescription()
	{
		return getChineseDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ChineseDescription
	 */
	public final String getChineseDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ChineseDescription.toString());
	}

	/**
	 * Set value of ChineseDescription
	 * @param chinesedescription
	 */
	public final void setChineseDescription(String chinesedescription)
	{
		setChineseDescription(getContext(), chinesedescription);
	}

	/**
	 * Set value of ChineseDescription
	 * @param context
	 * @param chinesedescription
	 */
	public final void setChineseDescription(IContext context, String chinesedescription)
	{
		getMendixObject().setValue(context, MemberNames.ChineseDescription.toString(), chinesedescription);
	}

	/**
	 * @return value of ArabicDescription
	 */
	public final String getArabicDescription()
	{
		return getArabicDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ArabicDescription
	 */
	public final String getArabicDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ArabicDescription.toString());
	}

	/**
	 * Set value of ArabicDescription
	 * @param arabicdescription
	 */
	public final void setArabicDescription(String arabicdescription)
	{
		setArabicDescription(getContext(), arabicdescription);
	}

	/**
	 * Set value of ArabicDescription
	 * @param context
	 * @param arabicdescription
	 */
	public final void setArabicDescription(IContext context, String arabicdescription)
	{
		getMendixObject().setValue(context, MemberNames.ArabicDescription.toString(), arabicdescription);
	}

	/**
	 * @return value of HebrewDescription
	 */
	public final String getHebrewDescription()
	{
		return getHebrewDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of HebrewDescription
	 */
	public final String getHebrewDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.HebrewDescription.toString());
	}

	/**
	 * Set value of HebrewDescription
	 * @param hebrewdescription
	 */
	public final void setHebrewDescription(String hebrewdescription)
	{
		setHebrewDescription(getContext(), hebrewdescription);
	}

	/**
	 * Set value of HebrewDescription
	 * @param context
	 * @param hebrewdescription
	 */
	public final void setHebrewDescription(IContext context, String hebrewdescription)
	{
		getMendixObject().setValue(context, MemberNames.HebrewDescription.toString(), hebrewdescription);
	}

	/**
	 * @return value of ThaiDescription
	 */
	public final String getThaiDescription()
	{
		return getThaiDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ThaiDescription
	 */
	public final String getThaiDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ThaiDescription.toString());
	}

	/**
	 * Set value of ThaiDescription
	 * @param thaidescription
	 */
	public final void setThaiDescription(String thaidescription)
	{
		setThaiDescription(getContext(), thaidescription);
	}

	/**
	 * Set value of ThaiDescription
	 * @param context
	 * @param thaidescription
	 */
	public final void setThaiDescription(IContext context, String thaidescription)
	{
		getMendixObject().setValue(context, MemberNames.ThaiDescription.toString(), thaidescription);
	}

	/**
	 * @return value of GermanDescription
	 */
	public final String getGermanDescription()
	{
		return getGermanDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of GermanDescription
	 */
	public final String getGermanDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.GermanDescription.toString());
	}

	/**
	 * Set value of GermanDescription
	 * @param germandescription
	 */
	public final void setGermanDescription(String germandescription)
	{
		setGermanDescription(getContext(), germandescription);
	}

	/**
	 * Set value of GermanDescription
	 * @param context
	 * @param germandescription
	 */
	public final void setGermanDescription(IContext context, String germandescription)
	{
		getMendixObject().setValue(context, MemberNames.GermanDescription.toString(), germandescription);
	}

	/**
	 * @return value of JapaneseDescription
	 */
	public final String getJapaneseDescription()
	{
		return getJapaneseDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of JapaneseDescription
	 */
	public final String getJapaneseDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.JapaneseDescription.toString());
	}

	/**
	 * Set value of JapaneseDescription
	 * @param japanesedescription
	 */
	public final void setJapaneseDescription(String japanesedescription)
	{
		setJapaneseDescription(getContext(), japanesedescription);
	}

	/**
	 * Set value of JapaneseDescription
	 * @param context
	 * @param japanesedescription
	 */
	public final void setJapaneseDescription(IContext context, String japanesedescription)
	{
		getMendixObject().setValue(context, MemberNames.JapaneseDescription.toString(), japanesedescription);
	}

	/**
	 * @return value of TurkishDescription
	 */
	public final String getTurkishDescription()
	{
		return getTurkishDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of TurkishDescription
	 */
	public final String getTurkishDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.TurkishDescription.toString());
	}

	/**
	 * Set value of TurkishDescription
	 * @param turkishdescription
	 */
	public final void setTurkishDescription(String turkishdescription)
	{
		setTurkishDescription(getContext(), turkishdescription);
	}

	/**
	 * Set value of TurkishDescription
	 * @param context
	 * @param turkishdescription
	 */
	public final void setTurkishDescription(IContext context, String turkishdescription)
	{
		getMendixObject().setValue(context, MemberNames.TurkishDescription.toString(), turkishdescription);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of Status
	 */
	public final String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final String getStatus(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(IContext context, String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Product_ProductSubcategory
	 */
	public final myfirstmodule.proxies.ProductSubcategory getProduct_ProductSubcategory() throws CoreException
	{
		return getProduct_ProductSubcategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Product_ProductSubcategory
	 */
	public final myfirstmodule.proxies.ProductSubcategory getProduct_ProductSubcategory(IContext context) throws CoreException
	{
		myfirstmodule.proxies.ProductSubcategory result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Product_ProductSubcategory.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.ProductSubcategory.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Product_ProductSubcategory
	 * @param product_productsubcategory
	 */
	public final void setProduct_ProductSubcategory(myfirstmodule.proxies.ProductSubcategory product_productsubcategory)
	{
		setProduct_ProductSubcategory(getContext(), product_productsubcategory);
	}

	/**
	 * Set value of Product_ProductSubcategory
	 * @param context
	 * @param product_productsubcategory
	 */
	public final void setProduct_ProductSubcategory(IContext context, myfirstmodule.proxies.ProductSubcategory product_productsubcategory)
	{
		if (product_productsubcategory == null)
			getMendixObject().setValue(context, MemberNames.Product_ProductSubcategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Product_ProductSubcategory.toString(), product_productsubcategory.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return productMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Product that = (myfirstmodule.proxies.Product) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Product";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
