// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Promotion
{
	private final IMendixObject promotionMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Promotion";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PromotionKey("PromotionKey"),
		PromotionAlternateKey("PromotionAlternateKey"),
		EnglishPromotionName("EnglishPromotionName"),
		SpanishPromotionName("SpanishPromotionName"),
		FrenchPromotionName("FrenchPromotionName"),
		DiscountPct("DiscountPct"),
		EnglishPromotionType("EnglishPromotionType"),
		SpanishPromotionType("SpanishPromotionType"),
		FrenchPromotionType("FrenchPromotionType"),
		EnglishPromotionCategory("EnglishPromotionCategory"),
		SpanishPromotionCategory("SpanishPromotionCategory"),
		FrenchPromotionCategory("FrenchPromotionCategory"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		MinQty("MinQty"),
		MaxQty("MaxQty"),
		Promotion_InternetSales("MyFirstModule.Promotion_InternetSales");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Promotion(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Promotion"));
	}

	protected Promotion(IContext context, IMendixObject promotionMendixObject)
	{
		if (promotionMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Promotion", promotionMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Promotion");

		this.promotionMendixObject = promotionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Promotion(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Promotion create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.Promotion");
		return new myfirstmodule.proxies.Promotion(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Promotion.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Promotion initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Promotion.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Promotion initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Promotion(context, mendixObject);
	}

	public static myfirstmodule.proxies.Promotion load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Promotion.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Promotion> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Promotion> result = new java.util.ArrayList<myfirstmodule.proxies.Promotion>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Promotion" + xpathConstraint))
			result.add(myfirstmodule.proxies.Promotion.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PromotionKey
	 */
	public final Integer getPromotionKey()
	{
		return getPromotionKey(getContext());
	}

	/**
	 * @param context
	 * @return value of PromotionKey
	 */
	public final Integer getPromotionKey(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.PromotionKey.toString());
	}

	/**
	 * Set value of PromotionKey
	 * @param promotionkey
	 */
	public final void setPromotionKey(Integer promotionkey)
	{
		setPromotionKey(getContext(), promotionkey);
	}

	/**
	 * Set value of PromotionKey
	 * @param context
	 * @param promotionkey
	 */
	public final void setPromotionKey(IContext context, Integer promotionkey)
	{
		getMendixObject().setValue(context, MemberNames.PromotionKey.toString(), promotionkey);
	}

	/**
	 * @return value of PromotionAlternateKey
	 */
	public final Integer getPromotionAlternateKey()
	{
		return getPromotionAlternateKey(getContext());
	}

	/**
	 * @param context
	 * @return value of PromotionAlternateKey
	 */
	public final Integer getPromotionAlternateKey(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.PromotionAlternateKey.toString());
	}

	/**
	 * Set value of PromotionAlternateKey
	 * @param promotionalternatekey
	 */
	public final void setPromotionAlternateKey(Integer promotionalternatekey)
	{
		setPromotionAlternateKey(getContext(), promotionalternatekey);
	}

	/**
	 * Set value of PromotionAlternateKey
	 * @param context
	 * @param promotionalternatekey
	 */
	public final void setPromotionAlternateKey(IContext context, Integer promotionalternatekey)
	{
		getMendixObject().setValue(context, MemberNames.PromotionAlternateKey.toString(), promotionalternatekey);
	}

	/**
	 * @return value of EnglishPromotionName
	 */
	public final String getEnglishPromotionName()
	{
		return getEnglishPromotionName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishPromotionName
	 */
	public final String getEnglishPromotionName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishPromotionName.toString());
	}

	/**
	 * Set value of EnglishPromotionName
	 * @param englishpromotionname
	 */
	public final void setEnglishPromotionName(String englishpromotionname)
	{
		setEnglishPromotionName(getContext(), englishpromotionname);
	}

	/**
	 * Set value of EnglishPromotionName
	 * @param context
	 * @param englishpromotionname
	 */
	public final void setEnglishPromotionName(IContext context, String englishpromotionname)
	{
		getMendixObject().setValue(context, MemberNames.EnglishPromotionName.toString(), englishpromotionname);
	}

	/**
	 * @return value of SpanishPromotionName
	 */
	public final String getSpanishPromotionName()
	{
		return getSpanishPromotionName(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanishPromotionName
	 */
	public final String getSpanishPromotionName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SpanishPromotionName.toString());
	}

	/**
	 * Set value of SpanishPromotionName
	 * @param spanishpromotionname
	 */
	public final void setSpanishPromotionName(String spanishpromotionname)
	{
		setSpanishPromotionName(getContext(), spanishpromotionname);
	}

	/**
	 * Set value of SpanishPromotionName
	 * @param context
	 * @param spanishpromotionname
	 */
	public final void setSpanishPromotionName(IContext context, String spanishpromotionname)
	{
		getMendixObject().setValue(context, MemberNames.SpanishPromotionName.toString(), spanishpromotionname);
	}

	/**
	 * @return value of FrenchPromotionName
	 */
	public final String getFrenchPromotionName()
	{
		return getFrenchPromotionName(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchPromotionName
	 */
	public final String getFrenchPromotionName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchPromotionName.toString());
	}

	/**
	 * Set value of FrenchPromotionName
	 * @param frenchpromotionname
	 */
	public final void setFrenchPromotionName(String frenchpromotionname)
	{
		setFrenchPromotionName(getContext(), frenchpromotionname);
	}

	/**
	 * Set value of FrenchPromotionName
	 * @param context
	 * @param frenchpromotionname
	 */
	public final void setFrenchPromotionName(IContext context, String frenchpromotionname)
	{
		getMendixObject().setValue(context, MemberNames.FrenchPromotionName.toString(), frenchpromotionname);
	}

	/**
	 * @return value of DiscountPct
	 */
	public final Double getDiscountPct()
	{
		return getDiscountPct(getContext());
	}

	/**
	 * @param context
	 * @return value of DiscountPct
	 */
	public final Double getDiscountPct(IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.DiscountPct.toString());
	}

	/**
	 * Set value of DiscountPct
	 * @param discountpct
	 */
	public final void setDiscountPct(Double discountpct)
	{
		setDiscountPct(getContext(), discountpct);
	}

	/**
	 * Set value of DiscountPct
	 * @param context
	 * @param discountpct
	 */
	public final void setDiscountPct(IContext context, Double discountpct)
	{
		getMendixObject().setValue(context, MemberNames.DiscountPct.toString(), discountpct);
	}

	/**
	 * @return value of EnglishPromotionType
	 */
	public final String getEnglishPromotionType()
	{
		return getEnglishPromotionType(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishPromotionType
	 */
	public final String getEnglishPromotionType(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishPromotionType.toString());
	}

	/**
	 * Set value of EnglishPromotionType
	 * @param englishpromotiontype
	 */
	public final void setEnglishPromotionType(String englishpromotiontype)
	{
		setEnglishPromotionType(getContext(), englishpromotiontype);
	}

	/**
	 * Set value of EnglishPromotionType
	 * @param context
	 * @param englishpromotiontype
	 */
	public final void setEnglishPromotionType(IContext context, String englishpromotiontype)
	{
		getMendixObject().setValue(context, MemberNames.EnglishPromotionType.toString(), englishpromotiontype);
	}

	/**
	 * @return value of SpanishPromotionType
	 */
	public final String getSpanishPromotionType()
	{
		return getSpanishPromotionType(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanishPromotionType
	 */
	public final String getSpanishPromotionType(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SpanishPromotionType.toString());
	}

	/**
	 * Set value of SpanishPromotionType
	 * @param spanishpromotiontype
	 */
	public final void setSpanishPromotionType(String spanishpromotiontype)
	{
		setSpanishPromotionType(getContext(), spanishpromotiontype);
	}

	/**
	 * Set value of SpanishPromotionType
	 * @param context
	 * @param spanishpromotiontype
	 */
	public final void setSpanishPromotionType(IContext context, String spanishpromotiontype)
	{
		getMendixObject().setValue(context, MemberNames.SpanishPromotionType.toString(), spanishpromotiontype);
	}

	/**
	 * @return value of FrenchPromotionType
	 */
	public final String getFrenchPromotionType()
	{
		return getFrenchPromotionType(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchPromotionType
	 */
	public final String getFrenchPromotionType(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchPromotionType.toString());
	}

	/**
	 * Set value of FrenchPromotionType
	 * @param frenchpromotiontype
	 */
	public final void setFrenchPromotionType(String frenchpromotiontype)
	{
		setFrenchPromotionType(getContext(), frenchpromotiontype);
	}

	/**
	 * Set value of FrenchPromotionType
	 * @param context
	 * @param frenchpromotiontype
	 */
	public final void setFrenchPromotionType(IContext context, String frenchpromotiontype)
	{
		getMendixObject().setValue(context, MemberNames.FrenchPromotionType.toString(), frenchpromotiontype);
	}

	/**
	 * @return value of EnglishPromotionCategory
	 */
	public final String getEnglishPromotionCategory()
	{
		return getEnglishPromotionCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishPromotionCategory
	 */
	public final String getEnglishPromotionCategory(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EnglishPromotionCategory.toString());
	}

	/**
	 * Set value of EnglishPromotionCategory
	 * @param englishpromotioncategory
	 */
	public final void setEnglishPromotionCategory(String englishpromotioncategory)
	{
		setEnglishPromotionCategory(getContext(), englishpromotioncategory);
	}

	/**
	 * Set value of EnglishPromotionCategory
	 * @param context
	 * @param englishpromotioncategory
	 */
	public final void setEnglishPromotionCategory(IContext context, String englishpromotioncategory)
	{
		getMendixObject().setValue(context, MemberNames.EnglishPromotionCategory.toString(), englishpromotioncategory);
	}

	/**
	 * @return value of SpanishPromotionCategory
	 */
	public final String getSpanishPromotionCategory()
	{
		return getSpanishPromotionCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanishPromotionCategory
	 */
	public final String getSpanishPromotionCategory(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SpanishPromotionCategory.toString());
	}

	/**
	 * Set value of SpanishPromotionCategory
	 * @param spanishpromotioncategory
	 */
	public final void setSpanishPromotionCategory(String spanishpromotioncategory)
	{
		setSpanishPromotionCategory(getContext(), spanishpromotioncategory);
	}

	/**
	 * Set value of SpanishPromotionCategory
	 * @param context
	 * @param spanishpromotioncategory
	 */
	public final void setSpanishPromotionCategory(IContext context, String spanishpromotioncategory)
	{
		getMendixObject().setValue(context, MemberNames.SpanishPromotionCategory.toString(), spanishpromotioncategory);
	}

	/**
	 * @return value of FrenchPromotionCategory
	 */
	public final String getFrenchPromotionCategory()
	{
		return getFrenchPromotionCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of FrenchPromotionCategory
	 */
	public final String getFrenchPromotionCategory(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FrenchPromotionCategory.toString());
	}

	/**
	 * Set value of FrenchPromotionCategory
	 * @param frenchpromotioncategory
	 */
	public final void setFrenchPromotionCategory(String frenchpromotioncategory)
	{
		setFrenchPromotionCategory(getContext(), frenchpromotioncategory);
	}

	/**
	 * Set value of FrenchPromotionCategory
	 * @param context
	 * @param frenchpromotioncategory
	 */
	public final void setFrenchPromotionCategory(IContext context, String frenchpromotioncategory)
	{
		getMendixObject().setValue(context, MemberNames.FrenchPromotionCategory.toString(), frenchpromotioncategory);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of MinQty
	 */
	public final Integer getMinQty()
	{
		return getMinQty(getContext());
	}

	/**
	 * @param context
	 * @return value of MinQty
	 */
	public final Integer getMinQty(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.MinQty.toString());
	}

	/**
	 * Set value of MinQty
	 * @param minqty
	 */
	public final void setMinQty(Integer minqty)
	{
		setMinQty(getContext(), minqty);
	}

	/**
	 * Set value of MinQty
	 * @param context
	 * @param minqty
	 */
	public final void setMinQty(IContext context, Integer minqty)
	{
		getMendixObject().setValue(context, MemberNames.MinQty.toString(), minqty);
	}

	/**
	 * @return value of MaxQty
	 */
	public final Integer getMaxQty()
	{
		return getMaxQty(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxQty
	 */
	public final Integer getMaxQty(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.MaxQty.toString());
	}

	/**
	 * Set value of MaxQty
	 * @param maxqty
	 */
	public final void setMaxQty(Integer maxqty)
	{
		setMaxQty(getContext(), maxqty);
	}

	/**
	 * Set value of MaxQty
	 * @param context
	 * @param maxqty
	 */
	public final void setMaxQty(IContext context, Integer maxqty)
	{
		getMendixObject().setValue(context, MemberNames.MaxQty.toString(), maxqty);
	}

	/**
	 * @return value of Promotion_InternetSales
	 */
	public final myfirstmodule.proxies.InternetSales getPromotion_InternetSales() throws CoreException
	{
		return getPromotion_InternetSales(getContext());
	}

	/**
	 * @param context
	 * @return value of Promotion_InternetSales
	 */
	public final myfirstmodule.proxies.InternetSales getPromotion_InternetSales(IContext context) throws CoreException
	{
		myfirstmodule.proxies.InternetSales result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Promotion_InternetSales.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.InternetSales.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Promotion_InternetSales
	 * @param promotion_internetsales
	 */
	public final void setPromotion_InternetSales(myfirstmodule.proxies.InternetSales promotion_internetsales)
	{
		setPromotion_InternetSales(getContext(), promotion_internetsales);
	}

	/**
	 * Set value of Promotion_InternetSales
	 * @param context
	 * @param promotion_internetsales
	 */
	public final void setPromotion_InternetSales(IContext context, myfirstmodule.proxies.InternetSales promotion_internetsales)
	{
		if (promotion_internetsales == null)
			getMendixObject().setValue(context, MemberNames.Promotion_InternetSales.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Promotion_InternetSales.toString(), promotion_internetsales.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return promotionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Promotion that = (myfirstmodule.proxies.Promotion) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Promotion";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().getGuid();
	}
}
